server:
  port: 8088

spring:
#  main:
#    allow-bean-definition-overriding: false
#    allow-circular-references: true
  application:
    name: twitter-clone
  data:
    mongodb:
      username: daniel
      password: RfmWvjcnvNPGB4IW
      #       mongodb+srv://daniel:<password>@cluster.8f5h5em.mongodb.net/?retryWrites=true&w=majority
      uri: mongodb+srv://daniel:RfmWvjcnvNPGB4IW@cluster.8f5h5em.mongodb.net/?retryWrites=true&w=majority
      database: proxy_seller
      auto-index-creation: true

logging:
  level:
    root: INFO
    org.springframework:
#        security: DEBUG
        security: INFO