server:
  port: 8088

spring:
  application:
    name: social-network
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PSWD}@${DB_URI_URL}/${DB_URI_TAIL}
      database: proxy_seller
      auto-index-creation: true

logging:
  level:
    root: INFO
    org.springframework:
        security: INFO